version: '3'
services:
  mysql:
    image: mysql:8.1.0
    platform: linux/amd64
    restart: 'no'
    container_name: depoly-server
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=depoly-server
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Seoul
    ports:
      - '3306:3306'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--lower_case_table_names=1'
    volumes:
      - /Users/jaehyungz/mysql-container/depoly-server:/var/lib/mysql
